name: Update Product Database
on:
  schedule:
    - cron: '0 2 * * 0,1,5'  # Runs at 02:00 UTC on Sunday, Monday, and Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: DKSD secret keys
    env:
      # API Configuration
      API_KEY: ${{ secrets.API_KEY }}
      TRACK_ID: ${{ secrets.TRACK_ID }}
      BUSINESS_IDS: ${{ secrets.BUSINESS_IDS }}
      
      # Firebase Configuration
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      
      # Firebase Admin Authentication
      FIREBASE_ADMIN_EMAIL: ${{ secrets.FIREBASE_ADMIN_EMAIL }}
      FIREBASE_ADMIN_PASSWORD: ${{ secrets.FIREBASE_ADMIN_PASSWORD }}
      
      # Production settings
      NODE_ENV: production
      BYPASS_ADMIN_CHECK: false
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Debug Environment Variables (redacted)
        run: |
          echo "API_KEY=********"
          echo "FIREBASE_DATABASE_URL=${{ env.FIREBASE_DATABASE_URL }}"
          echo "NODE_ENV=${{ env.NODE_ENV }}"
          
      - name: Run data update process
        run: node src/index.js fetchAndProcessCatalogs
        
      - name: Notify on success
        if: success()
        run: echo "Database update completed successfully!"
        
      - name: Notify on failure
        if: failure()
        run: echo "Database update failed! Check logs for details."